name: client
description: Dart gRPC sample client.
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.5.1
  async: '>=1.13.3 <3.0.0'
  grpc: ^2.1.3
  protobuf: ^1.0.1

dev_dependencies:
  test: ^1.3.0