name: import_googleapis
description: Import APIs from the googleapis repository on GitHub.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  importer:
    path: ../importer
  registry:
    path: ../../registry
  archive: ^2.0.13
  http: ^0.12.1
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
