name: compute_summary
description: Compute a summary of Registry contents.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  registry:
    path: ../../registry
  archive: ^3.0.0
  http: ^0.13.1
  grpc: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
