name: import_discovery
description: Import APIs from the Google API Discovery Service.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  importer:
    path: ../importer
  registry:
    path: ../../registry
  archive: ^3.0.0
  http: ^0.13.0
  grpc: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
