name: Flutter

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get protoc
      run: |
        sudo curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protoc-3.13.0-linux-x86_64.zip > /tmp/protoc.zip
        sudo unzip /tmp/protoc.zip -d /usr/local
        sudo chown -R $USER /usr/local
        ln -s /usr/local $HOME/local
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    - name: Get Dart protoc plugin
      run: |
        flutter pub global activate protoc_plugin
        echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
    - run: flutter config --enable-web
    - run: make create
    - run: make protos
    - run: make staging
