name: Flutter

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install protoc
      run: |
        sudo curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.20.1/protoc-3.20.1-linux-x86_64.zip > /tmp/protoc.zip
        sudo unzip /tmp/protoc.zip -d /usr/local
        sudo chown -R $USER /usr/local
    - name: Install Flutter tools
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'
        channel: 'stable'
    - name: Add Flutter .pub-cache to PATH
      run: |
        echo "$FLUTTER_HOME/.pub-cache/bin" >> $GITHUB_PATH
    - name: Install Dart protoc plugin
      run: |
        echo $PATH
        flutter pub global activate protoc_plugin
    - name: "Update apt package cache"
      run: sudo apt-get update
    - name: "Install Linux build dependencies"
      run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
    - name: "Enable target platforms"
      run: flutter config --enable-web --enable-linux-desktop
    - name: Generate flutter project scaffolding
      run: make create
    - name: Generate protobuf support code
      run: make protos
    - name: Build the linux target
      run: make linux
    - name: Build the web target
      run: make web
    - name: Build the reg command-line tool
      run: |
        cd apps/reg
        flutter pub get
        make
